### PR TITLE
Create stale.yaml

### PR DESCRIPTION
**Pull request by dekuhn**
adding real-time-enforcer repo probot-stale configuration

### CODE REVIEW

**Comment by jceresini** [comment]
There's not really any activity on this repo outside of ClearDATA, so do we really need this? It will, however, make your issue (#12) stale right away. We don't have access to setup the GCR stuff, so we couldn't address that issue if we wanted to.

**Comment by dekuhn** [comment]
If you prefer not to enable this I will revert the PR.

The config as it stands today would only make issues stale at 180 days. It would warn at 152 days if there have been no comments within the last 152 days. If there are recent comments then the clock is reset. 

The PR stale settings would warn at 30 and close if no updates at 37 days.

**Comment by jceresini** [comment]
Right, i have no problem with it, but the only thing it will affect currently is an issue you submitted back in June that is still outstanding. If you're aware of that and still want it merged im happy to merge it

**Comment by dekuhn** [comment]
SGTM, lets proceed. Thanks!

**Pull request merged**
